######################################################################
# Automatically generated by qmake (3.0) ?? 1? 11 18:17:00 2016
######################################################################

TEMPLATE = app
TARGET = QVcomTest
INCLUDEPATH += .

QT += core
QT += widgets
QT += gui
QT += serialport

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES +=  main.cpp            \
            mainwindow.cpp      \
            simpletest.cpp      \
            result_disp.cpp     \
            port_behavior.cpp   \
            inhometest.cpp      \
